---
- name: copy mongobackup script
  template:
    src: "mongobackup.sh"
    dest: "/usr/local/bin/mongobackup.sh"
    mode: 0755
  tags:
    - mongo
    - backup

- name: setup daily mongo backup
  cron:
    name: "daily mongo backup"
    minute: "5"
    hour: "{{ mongo_backup_hour }}"
    job: "/usr/local/bin/mongobackup.sh > /dev/null 2>&1"
  tags:
    - cron
    - mongo
    - backup
